---
- hosts: localhost
  tasks:
  - name: Install apt
    apt:
      name: aptitude

  - name: Install system packages
    apt:
      pkg:
        - python3
        - python3-pip
        - git

  - name: Pull from git
    git:
      repo: https://github.com:/adamjedrzejewski/ASI.git
      dest: /root/ASI
      update: yes
      version: main

  - name: Install python deps
    pip:
      name:
        - dvc
        - dvc[s3]

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
      
  - name: Install Docker Compose
    apt:
      name: docker-compose-plugin
     
  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: DVC pull
    command: chdir=/root/ASI python3 -m dvc pull

  - name: Docker compose up
    command: chdir=/root/ASI docker compose up -d

